restructure_topics:
  response_mime_type: application/json

  system_instruction: >
    Você receberá **um único objeto em JSON** com a seguinte estrutura:

    ```json
    {
      "topics": [
        {
          "topic": "Título ou nome do capítulo/subcapítulo",
          "sub_topics": [
            "Conceito-chave aprofundado em texto corrido",
            "Conceito-chave aprofundado em texto corrido"
          ]
        },
        ...
      ]
    }
    ```

    Você também receberá um JSON com os diretórios existentes no formato:
    ```json
    {
      "existing_directories": [
        "Nome do diretório 1",
        "Nome do diretório 2"
      ]
    }
    ```

    Seu objetivo é **reorganizar** os tópicos e sub-tópicos de forma a torná-los mais didáticos, lógicos e estruturados, **sem perder nenhuma informação e sem repetições**. Ao reorganizar, dê preferência para usar os nomes de diretórios existentes como tópicos sempre que fizer sentido semanticamente.

    ### Diretrizes para a reorganização:
    1. **Estrutura e hierarquia**  
       - Respeite a estrutura `"topics" -> "sub_topics"`.  
       - Se necessário, reorganize a ordem dos tópicos para que o conteúdo fique mais claro e progressivo.  
       - Sempre que possível, use os nomes dos diretórios existentes como tópicos.

    2. **Unificação de conteúdo**  
       - Caso existam tópicos ou sub-tópicos repetidos ou que tratem do mesmo assunto, combine-os em uma única entrada, mesclando o conteúdo.  
       - Exclua apenas redundâncias literais, sem perder detalhes ou exemplos.  
       - Garanta que cada sub-tópico seja autocontido e focado em um conceito específico.

    3. **Resultado Final**  
       - Retorne **apenas o JSON** resultante, mantendo a estrutura:  
         ```json
         {
           "topics": [
             {
               "topic": "Título (ou nome do diretório, se aplicável)",
               "sub_topics": [
                 "Conteúdo resultante da fusão e reorganização..."
               ]
             },
             ...
           ]
         }
         ```
       - Não inclua texto adicional além do objeto JSON em si.
       - Assegure-se de que o JSON seja **válido** e mantenha a coerência de tópicos e sub-tópicos.

    ```json
    {
      "type": "object",
      "properties": {
        "topics": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "topic": {
                "type": "string"
              },
              "sub_topics": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "topic",
              "sub_topics"
            ]
          }
        }
      },
      "required": [
        "topics"
      ]
    }
    ```

    Em resumo: você deve **reorganizar** os tópicos e sub-tópicos de um único JSON, unificar conteúdos redundantes e aproveitar o nome de diretórios já existentes se fizer sentido, **retornando apenas o JSON final** sem perda de informações.

  user_message: >
    Reestruture o JSON fornecido para que seus tópicos e sub-tópicos fiquem mais claros e didáticos, fazendo uso, quando possível, dos diretórios já existentes:

    {content}

    Lembre-se de:
    1. Manter apenas um campo "topics"
    2. Evitar repetições e manter todo o conteúdo
    3. Aproveitar nomes de diretórios existentes, se fizer sentido